### ISSUE TITLE
Code review (plot 외)

### ISSUE THREAD

**Issue by NamYehyun** [SNUCSE-CTA/graph-analysis-tool#14]
큰 의미는 없지만 개선하면 좋을 법 한 사항이 몇 가지 있습니다.
- [x] 입력 데이터에 label 정보가 없는 경우, 결과 html의 label-vertex image 단락에 *엑스박스*가 보여집니다. `label-vertex.py`의 line 19에 있는 조건문을 통과하지 못해 이미지 파일 자체가 생성되지 않기 때문입니다. *엑스박스*를 보여주는 것 보다는, 조건문을 지워서 (축밖에 없긴 하지만) 정상적인 이미지를 생성하고 보여주는 것이 좋을 것 같습니다.
https://github.com/SNUCSE-CTA/graph-analysis-tool/blob/89b10dd92e0e798ba25e18ddc15c20c7f12e7930/label-vertex.py#L19-L24

- [x] 이미지를 그리는 python파일들(`degree.py` 등)은 command-line argument로 `graph_name`을 받습니다. 이것은 정말 그래프 이름은 아니고, `makeplot`에서 `plot->id`를 넘겨주는 것인데, 단순한 정수값입니다. 그래서 python파일들이 생성하는 이미지의 이름은 그래프의 이름과 무관하게  `0_degree.png`등이 되고, 이 때문에 매 프로그램 실행마다 이미지가 덮어쓰기 되어서 이전 실행의 결과물이 보존되지 않습니다. 마침 pull request #13 에서 그래프 이름을 정하는 로직이 구현되었으니 `plot`과 `makeplot`을 조금 고쳐 실제 그래프 이름을 넘겨주도록 수정할 수 있을 것 같습니다.
https://github.com/SNUCSE-CTA/graph-analysis-tool/blob/89b10dd92e0e798ba25e18ddc15c20c7f12e7930/degree.py#L7
https://github.com/SNUCSE-CTA/graph-analysis-tool/blob/89b10dd92e0e798ba25e18ddc15c20c7f12e7930/makeplot.cpp#L33-L35
https://github.com/SNUCSE-CTA/graph-analysis-tool/blob/89b10dd92e0e798ba25e18ddc15c20c7f12e7930/plot.cpp#L6-L10

**Comment by gmgu** [comment]
개선 사항들이 pull request [#16](https://github.com/SNUCSE-CTA/graph-analysis-tool/pull/16)에서 수정되었습니다.
