### ISSUE TITLE
Code review (main.cpp, parse.h, parse.cpp)

### ISSUE THREAD

**Issue by NamYehyun** [SNUCSE-CTA/graph-analysis-tool#7]
`main`과 `parse`를 아래와 같이 개선하고자 합니다.
- [x] `main`에 하드코딩 되어있는 입력 데이터들을 제거하고 이후에는 command-line argument의 형태로 입력받을 것입니다.
- [x] `parse`에 정의되어 있는 `parse_xxx_XXGraph`등을 수정하여 이들이 입력 데이터 파싱이 어떻게 진행되었는가에 대해 상태값을 반환하도록 할 것 입니다.  `main`에서는 그 값을 읽고 적절한 대응(에러 메시지 출력 등)을 할 수 있습니다.

**Comment by gmgu** [comment]
제기된 문제들이 pull request [#8](https://github.com/SNUCSE-CTA/graph-analysis-tool/pull/8)에서 모두 해결되었습니다.
